name: Issues Workflow

on:
  issues:
    types:
      - opened
      - reopened
      - closed
      - assigned
      - labeled

jobs:
  notify-users:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        run:
          echo "Need to make this action"